#!/bin/sh
make &&
./update_image.sh &&
#sudo qemu -net tap nic,model=rtl8139,vlan=0,macaddr=5c:ac:4c:56:46:ab -fda floppy.img
sudo qemu -net nic,model=rtl8139,vlan=0,macaddr=5c:ac:4c:56:46:ac -fda floppy.img
#sudo qemu -net nic,model=rtl8139,vlan=0,macaddr=ff:ff:ff:ff:ff:ff -fda floppy.img
